---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-etc-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: glusterfs-storage-block
  labels:
    app: splunk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-var-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: glusterfs-storage-block
  labels:
    app: splunk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

